# Generated by Django 5.0.2 on 2024-03-28 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecieverBankLog',
            fields=[
                ('transaction_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('from_user', models.CharField(max_length=20, null=True)),
                ('to_user', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recieverbank',
            name='last_transaction',
        ),
        migrations.RemoveField(
            model_name='recieverbank',
            name='transaction_log',
        ),
        migrations.RemoveField(
            model_name='recieverbank',
            name='user',
        ),
        migrations.AddField(
            model_name='recieverbank',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recieverbank',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recieverbank',
            name='transaction_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
