# Generated by Django 5.0.2 on 2024-03-29 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0002_recieverbanklog_remove_recieverbank_last_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivermoredetails',
            name='registered_ngo',
        ),
        migrations.AddField(
            model_name='receivermoredetails',
            name='is_reciever_type_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receivermoredetails',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ngo_reciever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ngo_defined', models.BooleanField(default=False)),
                ('ngo', models.CharField(max_length=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
