# Generated by Django 5.0.2 on 2024-04-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0006_rename_ting_quantity_recieverrequests_thing_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieverrequests',
            name='desc',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='recieverrequests',
            name='for_what',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
