# Generated by Django 5.0.2 on 2024-04-22 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0007_recieverrequests_desc_recieverrequests_for_what'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecieverRequestGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing_name', models.CharField(blank=True, max_length=20)),
                ('thing_quantity', models.IntegerField(null=True)),
                ('for_what', models.CharField(blank=True, max_length=40)),
                ('desc', models.CharField(blank=True, max_length=150)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_request_goods', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_request_goods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
