# Generated by Django 4.2.4 on 2024-04-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0010_recieverresidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivermoredetails',
            name='residents_count',
            field=models.IntegerField(null=True),
        ),
    ]
