# Generated by Django 5.0.2 on 2024-04-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngousers',
            name='is_balanced_defined',
            field=models.BooleanField(default=False),
        ),
    ]
