# Generated by Django 5.0.2 on 2024-04-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_ngousers_is_balanced_defined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngousers',
            old_name='is_balanced_defined',
            new_name='is_balance_defined',
        ),
    ]
