# Generated by Django 5.0.2 on 2024-03-30 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_reciever_under_ngo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciever_under_ngo',
            name='reciever',
        ),
        migrations.AddField(
            model_name='reciever_under_ngo',
            name='ngo_receivers',
            field=models.ManyToManyField(related_name='received_ngos', to=settings.AUTH_USER_MODEL),
        ),
    ]
