# Generated by Django 5.0.2 on 2024-03-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_remove_reciever_under_ngo_reciever_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciever_under_ngo',
            old_name='ngo_receivers',
            new_name='reciever',
        ),
    ]
