# Generated by Django 5.0.2 on 2024-03-30 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_rename_ngo_receivers_reciever_under_ngo_reciever'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciever_under_ngo',
            name='reciever',
        ),
        migrations.AlterField(
            model_name='reciever_under_ngo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ngos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reciever_under_ngo',
            name='reciever',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_ngos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
