# Generated by Django 5.0.2 on 2024-04-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0008_remove_ngobank_last_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngobank',
            name='is_balanced_defined',
            field=models.BooleanField(default=False),
        ),
    ]
