# Generated by Django 5.0.2 on 2024-04-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0009_ngobank_is_balanced_defined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngobank',
            name='is_balanced_defined',
        ),
    ]
