# Generated by Django 5.0.2 on 2024-04-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0011_ngobanktransactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngobanktransactions',
            old_name='current_balance',
            new_name='amount',
        ),
    ]
