# Generated by Django 5.0.2 on 2024-04-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0012_rename_current_balance_ngobanktransactions_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngobanktransactions',
            name='transaction_type',
            field=models.CharField(choices=[('credited', 'credited'), ('debited', 'debited')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='ngobanktransactions',
            name='transaction_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
