# Generated by Django 5.0.2 on 2024-04-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0013_ngobanktransactions_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngobanktransactions',
            name='transaction_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
