# Generated by Django 5.0.2 on 2024-04-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0015_ngobanktransactions_done_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngobanktransactions',
            name='done_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
